travis:
  secure:
    BINSTAR_TOKEN: OXGC+z+xWJIBiODS4HOKuZ+cZKByJR4yyxERrMvUvfUjlCUU0PMvuxiMPQyB+8F3X50edvxI/rMeY69VRN86GTvjE8dCTn0qcvNHx+/q49Sn3XnG69ipSMsoFdy0ENPxyNqQJ9f9/+nwHs5It7NHr+rOeUtbUQyhYL4OQYBDniysDtenyhl3DZF7C+JLkxQZGIK6OG2iZf42kndXqjixD5fZBTtXV8epjlhrApB8GfeMfeeZs24RUKOnx2CFC6Ni+hJCgBB9dHhiWeco1AmohiGmbDaiOdp43WqaoTHABx1mdTGRZbHHis5roQ2VM9rkXmRMgF/zmk3yofvfewY2SYH4OUW4rR6/lh+3V70ePhWlZ3UFYaLgj0lLg0zRmq8CRpD/SCtU7VpUjmMvuVDBVbWJx0TudoiEcndMnUDnJFHOdb9gUEl1vnoIyYTIQWIux+psZiR+s39zzyBZUv7nYTSz0eIkvQo/PPZBzd0E/XajGJJ2xnhI6mhO6/ZgQ/Jp3bc/vXFuh3Trcub6N7h/Q/TxeppbmFN/RnT1NeU0OHv9L28nht9E0syXLqwndl+ZkeHVHjfjl/XJrGszusejXHO/ZQAObJrLBtZO3Dh2duRukLZmwwB0Dq/TvaFkt7klmDwrgDNUurQ1iLWCmg4WdCvT8clg9P1SfaYfpttj20w=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
